export default {
  HAD_ORDERED: "已下单",
  HAD_DISPATCHED: "已配单",
  HAD_CAR_STOPED: "已停车",
  IN_FETCHING_CAR: "取车中",
  WILL_BE_CONFIRMED: "待确认",
  FINISH_FETCHING: "已完成",
  ROLE_USER_CUSTOMER: "ROLE_CUSTOMER",
  ROLE_USER_SUPER_MANAGER: "ROLE_SUPER_MANAGER",
  ROLE_USER_PARKING_BOY: "ROLE_USER_PARKING_BOY"
};
